name : test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on : ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
<<<<<<< HEAD
          python-version: "3.x"
=======
          python-version: "3.x" 
>>>>>>> test

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
<<<<<<< HEAD
          python -m pytest -v tests
=======
          python -m pytest -v tests
>>>>>>> test
